apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: postgres
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres.postgres.svc.cluster.local -U royal -d royal_dispatch; do
                echo "Waiting for postgres..."; sleep 2;
              done
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      containers:
        - name: migrate
          image: migrate/migrate
          args:
            - -path=/migrations
            - -database=postgres://royal:$(POSTGRES_PASSWORD)@postgres.postgres.svc.cluster.local:5432/royal_dispatch?sslmode=disable
            - up
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: migrations
